inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3.1
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/**/*'
    - 'public/**/*'
    - 'spec/**/*'
    - 'tmp/**/*'
    - 'lib/**/*'
    - 'Rakefile'
    - 'Capfile'
    - 'Gemfile'
    - 'config.ru'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/UnneededInterpolation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Metrics/LineLength:
  Max: 200

Metrics/ClassLength:
  Max: 350

Metrics/PerceivedComplexity:
  Max: 8

Metrics/ModuleLength:
  Max: 350

Metrics/AbcSize:
  Max: 100

Metrics/MethodLength:
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 11

Style/EvalWithLocation:
  Enabled: false

Rails:
  Enabled: true

Rails/InverseOf:
  Enabled: false
