understand:
  -
    text: "I don't understand you."
    options:
      :attachments: [
        {
          title: '',
          image_url: 'http://bestanimations.com/Sci-Fi/StarWars/R2D2/r2d2-c3po-animated-gif-3.gif'
        }
      ]
  -
    text: 'Slack API'
    options:
      :attachments: [
              {
                  "fallback": "Required plain-text summary of the attachment.",
                  "color": "#36a64f",
                  "pretext": "Optional text that appears above the attachment block",
                  "author_name": "Bobby Tables",
                  "author_link": "http://flickr.com/bobby/",
                  "author_icon": "http://flickr.com/icons/bobby.jpg",
                  "title": "Slack API Documentation",
                  "title_link": "https://api.slack.com/",
                  "text": "Optional text that appears within the attachment",
                  "fields": [
                      {
                          "title": "Priority",
                          "value": "High",
                          "short": false
                      }
                  ],
                  "image_url": "http://my-website.com/path/to/image.jpg",
                  "thumb_url": "http://example.com/path/to/thumb.png",
                  "footer": "Slack API",
                  "footer_icon": "https://platform.slack-edge.com/img/default_application_icon.png",
                  "ts": 123456789
              }
          ]
thanks:
  -
    text: "Thanks bro! Have a nice day! :smiley: "
    options:
      :attachments: []

log:
  -
    text: 'Do you have any other projects to log? Write `no` to finish logging time.'
    options:
      :attachments: []
today:
  -
    text: 'Hey mate, what did you do today?'
    options:
      :attachments: []